# ---------------------------------------------------------------------------
# make_tts_corpus.ps1 - synthesise a router-vocabulary corpus with Windows SAPI
#
#   powershell -NoProfile -File scripts\make_tts_corpus.ps1
#   powershell -NoProfile -File scripts\make_tts_corpus.ps1 -Voice Zira -Rate -2
#
# WHY THIS EXISTS
#
# Every biasing check in this repo used LibriSpeech probes -- LAMPS -> LAMBS and
# friends. Nothing tested that the *router vocabulary* survives, which is the
# only vocabulary that matters. This gives that a floor, today, without waiting
# for anyone to record anything.
#
# WHAT IT IS NOT
#
# SAPI is clean, native, American English. It does NOT test the Vietnamese- or
# Indian-accent failure mode this project exists for. It isolates the other axis:
# does the model know these words at all, on easy audio?
#
# That makes it a floor, not a target. A phrase the model gets wrong on synthetic
# speech it will certainly get wrong in an accent. A phrase it gets right here may
# still fail badly on a real speaker. Read results in that direction only, and
# keep recording tests/data/clips with your own voice -- see tests/README.md.
#
# Output is 16 kHz / 16-bit / mono, matching src/audio_wasapi.cpp exactly, so the
# corpus decodes through the same path a live take does.
# ---------------------------------------------------------------------------
[CmdletBinding()]
param(
  # Substring of an installed voice name ("David", "Zira").
  [string]$Voice = 'David',
  # SAPI rate, -10..10. 0 is default; negative is slower.
  [int]$Rate = 0,
  # Where the wavs go. Kept apart from tests/data/clips on purpose: that
  # directory is for real recordings, and mixing synthetic audio into it would
  # quietly corrupt the only corpus that measures the actual problem.
  [string]$OutDir = 'tests/data/tts',
  [string]$Manifest = 'tests/data/manifest-tts.tsv',
  [switch]$Force
)

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$outAbs = Join-Path $root $OutDir
$manifestAbs = Join-Path $root $Manifest

# The 12 target scenarios, as sentences a user would actually say. Kept in sync
# with tests/data/manifest.tsv by hand -- if you add a scenario, add it here too.
$phrases = @(
  'what is my network status',
  'check network status',
  'how is the router doing',
  'show me the router status',
  'who is online right now',
  'list online devices',
  'is anyone playing games',
  'show gaming sessions',
  'turn on guest wifi',
  'turn off guest network',
  'enable guest wifi',
  'open qos',
  'what is each device doing',
  'set bandwidth limit fifty',
  'limit speed to one hundred',
  'block internet for my son',
  'unblock internet for my son',
  'block youtube on the tablet',
  'unblock facebook',
  'show wifi device info'
)

Add-Type -AssemblyName System.Speech

$synth = New-Object System.Speech.Synthesis.SpeechSynthesizer
try {
  $picked = $synth.GetInstalledVoices() |
    Where-Object { $_.VoiceInfo.Name -like "*$Voice*" } |
    Select-Object -First 1
  if ($null -eq $picked) {
    $have = ($synth.GetInstalledVoices() | ForEach-Object { $_.VoiceInfo.Name }) -join ', '
    throw "no installed voice matches '$Voice'. Available: $have"
  }
  $synth.SelectVoice($picked.VoiceInfo.Name)
  $synth.Rate = $Rate

  if (-not (Test-Path $outAbs)) { New-Item -ItemType Directory -Force $outAbs | Out-Null }

  # 16 kHz, 16-bit, mono -- the format the models want and the format
  # src/audio_wasapi.cpp asks WASAPI for.
  $fmt = New-Object System.Speech.AudioFormat.SpeechAudioFormatInfo(
    16000,
    [System.Speech.AudioFormat.AudioBitsPerSample]::Sixteen,
    [System.Speech.AudioFormat.AudioChannel]::Mono)

  $rows = New-Object System.Collections.Generic.List[string]
  $rows.Add('# GENERATED by scripts/make_tts_corpus.ps1 -- do not hand-edit.')
  $rows.Add('#')
  $rows.Add('# Synthetic speech, clean native American English. This measures')
  $rows.Add('# whether the models know the router vocabulary at all; it does NOT')
  $rows.Add('# measure the accent problem. A floor, not a target.')
  $rows.Add("# voice: $($picked.VoiceInfo.Name)   rate: $Rate   16 kHz / 16-bit / mono")
  $rows.Add('')

  $i = 0
  foreach ($p in $phrases) {
    $i++
    $name = 'tts-{0:d4}.wav' -f $i
    $path = Join-Path $outAbs $name
    if ((Test-Path $path) -and -not $Force) {
      Write-Host ("  skip  {0}  (--Force to redo)" -f $name)
    } else {
      $synth.SetOutputToWaveFile($path, $fmt)
      $synth.Speak($p)
      # Release the file before the next iteration touches it.
      $synth.SetOutputToNull()
      $len = (Get-Item $path).Length
      Write-Host ("  ok    {0}  {1,7:N0} B  '{2}'" -f $name, $len, $p)
    }
    # Manifest paths are relative to the manifest file itself.
    $rows.Add(("tts/{0}`t{1}" -f $name, $p))
  }

  Set-Content -Path $manifestAbs -Value $rows -Encoding utf8
  Write-Host ""
  Write-Host ("  wrote {0} ({1} phrases)" -f $Manifest, $phrases.Count)
  Write-Host ""
  Write-Host "  next:  build\bin\vcc_cli.exe --eval $Manifest"
}
finally {
  $synth.Dispose()
}
